### PR TITLE
Change ADD to COPY

### PR DESCRIPTION
**Pull request by farribeiro**
Because not need network access

### CODE REVIEW

**Comment by ronoaldo** [comment]
Nice catch, thanks for the contribution! I'm testing soon and will merge afterwards.

**Comment by ronoaldo** [comment]
Ref: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy

**Comment by farribeiro** [comment]
I known this reference, for this case better COPY , not extracting a compressed file and network use

**Comment by ronoaldo** [comment]
Yeah, I was just saving the best practice backing your PR for future reference. Merging now.

**Pull request merged**
